In [1]:
# Notebook 출력설정
# 주요 라이브러리 임포트

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
pd.set_option('display.max_colwidth', -1)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

%matplotlib inline
import matplotlib.pylab as plt
plt.rcParams["figure.figsize"] = (15,5)
plt.rcParams['lines.linewidth'] = 1
plt.rcParams['axes.grid'] = True
import seaborn as sns

In [2]:
# 원본 데이터셋 로드
dir_dataset = "C:/Users/0stix/Datasets/"
name_project = '2203-kaggle-tps2203'
df_train = pd.read_csv(dir_dataset+name_project+'/train.csv')
df_test = pd.read_csv(dir_dataset+name_project+'/test.csv')
df_sub = pd.read_csv(dir_dataset+name_project+'/sample_submission.csv')

len_train = len(df_train)
df_all = pd.concat([df_train, df_test], axis=0)
target = 'congestion'

In [8]:
df_v0 = pd.DataFrame()
df_v0['time'] = df_all['time'].values[::65]
v_ = df_all[target].values

for num_ in range(65):
    str_ = 'f_' + str(num_)
    df_v0[str_] = v_[num_::65]
    
df_v0.head()

64
f_64

                  time   f_0   f_1   f_2   f_3   f_4   f_5   f_6   f_7   f_8   f_9  f_10  f_11  f_12  f_13  f_14  f_15  f_16  f_17  f_18  f_19  f_20  f_21  f_22  f_23  f_24  f_25  f_26  f_27  f_28  f_29  f_30  f_31  f_32  f_33  f_34  f_35  f_36  f_37  f_38  f_39  f_40  f_41  f_42  f_43  f_44  f_45  f_46  f_47  f_48  f_49  f_50  f_51  f_52  f_53  f_54  f_55  f_56  f_57  f_58  f_59  f_60  f_61  f_62  f_63  f_64
0  1991-04-01 00:00:00  70.0  49.0  24.0  18.0  60.0  58.0  26.0  31.0  49.0  46.0  29.0  18.0  16.0  21.0  49.0  47.0  51.0  74.0  74.0  43.0  44.0  52.0  32.0  44.0  77.0  39.0  63.0  53.0  28.0  24.0  29.0  54.0  46.0  41.0  44.0  44.0  37.0  15.0  46.0  44.0  39.0  26.0  61.0  65.0  26.0  16.0  29.0  22.0  34.0  45.0  37.0  42.0  50.0  26.0  21.0  36.0  51.0  47.0  51.0  39.0  64.0  30.0  70.0  29.0  26.0
1  1991-04-01 00:20:00  70.0  49.0  24.0  26.0  64.0  55.0  57.0  41.0  40.0  46.0  32.0  24.0  33.0  17.0  52.0  48.0  51.0  71.0  32.0  43.0  43.0  52.0  32.0  61.0  30.0  44.0  50.0  41.0  37.0  24.0  39.0  54.0  37.0  16.0  47.0  44.0  41.0  15.0  47.0  44.0  69.0  61.0  65.0  45.0  47.0  16.0  29.0  17.0  34.0  52.0  37.0  36.0  46.0  17.0  21.0  10.0  51.0  50.0  58.0  33.0  67.0  30.0  80.0  29.0  57.0
2  1991-04-01 00:40:00  70.0  49.0  24.0  31.0  51.0  57.0  91.0  42.0  41.0  35.0  35.0  24.0  36.0  46.0  56.0  15.0  43.0  59.0  48.0  43.0  43.0  52.0  32.0  49.0  38.0  43.0  40.0  34.0  36.0  24.0  43.0  54.0  43.0  15.0  43.0  44.0  46.0  15.0  41.0  41.0  54.0  61.0  46.0  44.0  44.0  16.0  29.0  33.0  34.0  78.0  27.0  47.0  34.0  17.0  21.0  32.0  51.0  49.0  63.0  33.0  64.0  30.0  79.0  29.0  48.0
3  1991-04-01 01:00:00  70.0  49.0  24.0  36.0  51.0  46.0  49.0  39.0  44.0  58.0  33.0  24.0  20.0  50.0  47.0  31.0  34.0  59.0  51.0  43.0  78.0  52.0  32.0  34.0  48.0  39.0  51.0  42.0  24.0  24.0  50.0  54.0  36.0  15.0  45.0  44.0  33.0  15.0  33.0  42.0  56.0  63.0  48.0  50.0  35.0  16.0  29.0  38.0  34.0  83.0  28.0  35.0  27.0  22.0  21.0  60.0  51.0  49.0  52.0  33.0  33.0  30.0  77.0  29.0  44.0
4  1991-04-01 01:20:00  70.0  49.0  24.0  29.0  53.0  83.0  62.0  36.0  46.0  46.0  25.0  24.0  19.0  50.0  51.0  19.0  47.0  7.0   29.0  43.0  18.0  52.0  32.0  54.0  47.0  36.0  49.0  55.0  22.0  24.0  55.0  54.0  56.0  20.0  41.0  44.0  33.0  15.0  22.0  38.0  79.0  63.0  54.0  51.0  29.0  16.0  29.0  38.0  34.0  83.0  27.0  47.0  31.0  19.0  21.0  43.0  51.0  49.0  50.0  33.0  50.0  30.0  79.0  29.0  44.0